### ISSUE TITLE
Kubeone fasly identified a new host as broken host

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubeone#1301]
We recreated one control plane node via Terraform, remove the etcdmember and then run kubeone apply to add it again.
In about 2 out of 10 runs, kubeone complaints that the newly created node is broken, panic and stops.
A second run of kubeone is workin fine

```
time="09:23:04 UTC" level=error msg="Host \"mark-test-control-plane-2\" is broken and needs to be manually removed\n"
time="09:23:04 UTC" level=warning msg="Hosts must be removed in a correct order to preserve the Etcd quorum."
time="09:23:04 UTC" level=warning msg="Loss of the Etcd quorum can cause loss of all data!!!"
time="09:23:04 UTC" level=warning msg="After removing the recommended hosts, run 'kubeone apply' before removing any other host."
time="09:23:04 UTC" level=warning msg="The recommended removal order:"
time="09:23:04 UTC" level=warning msg="- \"mark-test-control-plane-2\""
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5549c6]
goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Major(...)
	github.com/Masterminds/semver@v1.4.2/version.go:131
github.com/Masterminds/semver.(*Version).Compare(0x0, 0xc000312050, 0x0)
	github.com/Masterminds/semver@v1.4.2/version.go:268 +0x26
github.com/Masterminds/semver.(*Version).GreaterThan(...)
	github.com/Masterminds/semver@v1.4.2/version.go:250
k8c.io/kubeone/pkg/state.(*Cluster).SafeToRepair(0xc0002d9600, 0xc00004d038, 0x6, 0xc000655b70, 0x1, 0x1)
	k8c.io/kubeone/pkg/state/cluster.go:203 +0x20d
k8c.io/kubeone/pkg/cmd.runApply(0xc0000b3500, 0xc0002fdc00, 0x0)
	k8c.io/kubeone/pkg/cmd/apply.go:228 +0x865
k8c.io/kubeone/pkg/cmd.applyCmd.func1(0xc00002f340, 0xc000065700, 0x0, 0x8, 0x0, 0x0)
	k8c.io/kubeone/pkg/cmd/apply.go:108 +0x85
github.com/spf13/cobra.(*Command).execute(0xc00002f340, 0xc000065600, 0x8, 0x8, 0xc00002f340, 0xc000065600)
	github.com/spf13/cobra@v0.0.6/command.go:840 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00002edc0, 0x0, 0x0, 0x44546a)
	github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.6/command.go:885
k8c.io/kubeone/pkg/cmd.Execute()
	k8c.io/kubeone/pkg/cmd/root.go:52 +0xdc
main.main()
	k8c.io/kubeone/main.go:24 +0x25
```

I see it in the kubeone verison 1.1.0 and 1.2.1 and flatcar as operationg system.

Any idea where to look, or what happen here?

**Comment by kron4eg** [comment]
>remove the etcdmember

For future, KubeOne automate this step, you don't need to do it manually.

**Comment by qeqar** [comment]
Ok, we were to fast! Wen we start the kube apply before the controller-manager removed the node from the cluster, we get this error.

So we no just test until the node is really gone from the cluster.
